#DB Setting
spring:
  datasource:
    url: "
    username: "r
    password: "
    driver-class-name: org.mariadb.jdbc.Driver
---

#Jpa Setting
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

---
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
---

#Jwt
jwt:
  secret:
---

#Redis
spring:
  redis:
    host: localhost
    port: 6379
---

#google login
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 310888433920-qcb4vaemu1jdb3aq3c9l988kreirbvrj.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
