
#DB Setting
spring:
    datasource:
        url: "jdbc:mysql://localhost/tubenova"
        username: "root"
        password: "0000"
        driver-class-name: com.mysql.cj.jdbc.Driver
---

#Jpa Setting
spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect

---
spring:
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false
    freemarker:
        cache: false
---

#Jwt
jwt:
    secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LUxpa2UtSm9icy1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtTGlrZS1Kb2Jz
---

## Redis
#spring:
#    redis:
#        host: localhost
#        port: 6379
---

# google login
spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 310888433920-qcb4vaemu1jdb3aq3c9l988kreirbvrj.apps.googleusercontent.com
                        client-secret: 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
                        scope: profile, email