package TubeNova.app.domain;

public enum Category {
    LIFESTYLE, MUSICNDANCE, BEAUTYNFASHION, FILMNANIMATION, KIDS, GAME, OUTDOOR, SPORTS, NEWSNPOLITIC, GOVERNAGENCY,
    ENTERTAINMENT, FOOD, CELEBRITY, SCIENCE, ANIMAL, HOBBY, VEHICLE, ECONOMY, EDUCATION, UNTITLED
}
